### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by martab0** [jbatynski/markdown_rep_2023-11#2]
Świetnie! Jest niemal wszystko, co było na zajęciach, a do tego porządny opis zagadnienia - do portfolio!

Co warto sprawdzić:
- nie jestem pewna, czy GitHub Pages wyświetlą listę referencji w oddzielnych wierszach - jeśli wyjdzie zbity blok tekstu, to albo daj po dwie spacje na koniec każdego wiersza, albo zrób z tego listę wypunktowaną lub numerowaną (w tym drugim przypadku GitHub Pages same zadbają o nowe wiersze).

Co można wypróbować (spoza programu zajęć):
- obrazek z "dymkiem",
- tabelkę (może znajdzie się jakieś sensowne zastosowanie) z wyrównaniem tekstu w tabeli do prawej, do lewej, centralnie.

**Comment by jbatynski** [comment]
Udało się opublikować. Jeśli to możliwe, byłoby świetnie gdybyśmy mogli przejść te kroki jeszcze raz w publikowaniu na GitHub Pages. Kilku rzeczy nie rozumiem. Przypisy po wprowadzeniu listy punktowanej uporządkowały się, jednak po opublikowaniu zniknęły hiperlinki. Jeszcze raz, wielkie dzięki za pomoc.
